definitions:
  main.AddReq:
    properties:
      age:
        description: 年龄
        example: 26
        type: integer
      gender:
        description: 性别
        example: 1
        type: integer
      name:
        description: 姓名
        example: 张三
        type: string
      other:
        $ref: '#/definitions/main.AddReqOther'
        description: 其它
    required:
    - age
    - gender
    - name
    type: object
  main.AddReqOther:
    properties:
      b:
        description: B
        example: b
        type: string
      c:
        description: C
        example: c
        type: string
    type: object
  main.AddRes:
    properties:
      id:
        description: id
        example: 1
        type: integer
    type: object
  main.DeleteReq:
    properties:
      id:
        description: 用户id
        example: 1
        type: integer
    type: object
  main.DeleteRes:
    type: object
info:
  contact:
    email: test@qq.com
    name: API Support
    url: test.com
  description: Golang api of demo
  title: 待测试的开发文档
  version: "1.0"
paths:
  /api/v1/add:
    post:
      description: 新增用户信息
      parameters:
      - description: http header 验证authorization
        in: header
        name: authorization
        required: true
        type: string
      - description: 查询参数
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/main.AddReq'
      responses:
        "200":
          description: 返回参数
          schema:
            $ref: '#/definitions/main.AddRes'
      tags:
      - 人员
  /api/v1/delete:
    post:
      description: 删除用户信息
      parameters:
      - description: 查询参数
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/main.DeleteReq'
      responses:
        "200":
          description: 返回参数
          schema:
            $ref: '#/definitions/main.DeleteRes'
      tags:
      - 人员
swagger: "2.0"
